/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"

	v1alpha1 "github.com/databendcloud/databend-operator/pkg/apis/databendlabs.io/v1alpha1"
	databendlabsiov1alpha1 "github.com/databendcloud/databend-operator/pkg/client/applyconfiguration/databendlabs.io/v1alpha1"
	scheme "github.com/databendcloud/databend-operator/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// TenantsGetter has a method to return a TenantInterface.
// A group's client should implement this interface.
type TenantsGetter interface {
	Tenants(namespace string) TenantInterface
}

// TenantInterface has methods to work with Tenant resources.
type TenantInterface interface {
	Create(ctx context.Context, tenant *v1alpha1.Tenant, opts v1.CreateOptions) (*v1alpha1.Tenant, error)
	Update(ctx context.Context, tenant *v1alpha1.Tenant, opts v1.UpdateOptions) (*v1alpha1.Tenant, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, tenant *v1alpha1.Tenant, opts v1.UpdateOptions) (*v1alpha1.Tenant, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.Tenant, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.TenantList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Tenant, err error)
	Apply(ctx context.Context, tenant *databendlabsiov1alpha1.TenantApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.Tenant, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, tenant *databendlabsiov1alpha1.TenantApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.Tenant, err error)
	TenantExpansion
}

// tenants implements TenantInterface
type tenants struct {
	*gentype.ClientWithListAndApply[*v1alpha1.Tenant, *v1alpha1.TenantList, *databendlabsiov1alpha1.TenantApplyConfiguration]
}

// newTenants returns a Tenants
func newTenants(c *DatabendlabsV1alpha1Client, namespace string) *tenants {
	return &tenants{
		gentype.NewClientWithListAndApply[*v1alpha1.Tenant, *v1alpha1.TenantList, *databendlabsiov1alpha1.TenantApplyConfiguration](
			"tenants",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *v1alpha1.Tenant { return &v1alpha1.Tenant{} },
			func() *v1alpha1.TenantList { return &v1alpha1.TenantList{} }),
	}
}
