/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	databendlabsiov1alpha1 "github.com/databendcloud/databend-operator/pkg/apis/databendlabs.io/v1alpha1"
	versioned "github.com/databendcloud/databend-operator/pkg/client/clientset/versioned"
	internalinterfaces "github.com/databendcloud/databend-operator/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/databendcloud/databend-operator/pkg/client/listers/databendlabs.io/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// WarehouseInformer provides access to a shared informer and lister for
// Warehouses.
type WarehouseInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.WarehouseLister
}

type warehouseInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewWarehouseInformer constructs a new informer for Warehouse type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewWarehouseInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredWarehouseInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredWarehouseInformer constructs a new informer for Warehouse type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredWarehouseInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.DatabendlabsV1alpha1().Warehouses(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.DatabendlabsV1alpha1().Warehouses(namespace).Watch(context.TODO(), options)
			},
		},
		&databendlabsiov1alpha1.Warehouse{},
		resyncPeriod,
		indexers,
	)
}

func (f *warehouseInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredWarehouseInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *warehouseInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&databendlabsiov1alpha1.Warehouse{}, f.defaultInformer)
}

func (f *warehouseInformer) Lister() v1alpha1.WarehouseLister {
	return v1alpha1.NewWarehouseLister(f.Informer().GetIndexer())
}
