apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: databend-operator
    app.kubernetes.io/managed-by: kustomize
  name: databend-operator
  namespace: {{ .Values.namespace }}
