/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/databendcloud/databend-operator/pkg/apis/databendlabs.io/v1alpha1"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/listers"
	"k8s.io/client-go/tools/cache"
)

// WarehouseLister helps list Warehouses.
// All objects returned here must be treated as read-only.
type WarehouseLister interface {
	// List lists all Warehouses in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.Warehouse, err error)
	// Warehouses returns an object that can list and get Warehouses.
	Warehouses(namespace string) WarehouseNamespaceLister
	WarehouseListerExpansion
}

// warehouseLister implements the WarehouseLister interface.
type warehouseLister struct {
	listers.ResourceIndexer[*v1alpha1.Warehouse]
}

// NewWarehouseLister returns a new WarehouseLister.
func NewWarehouseLister(indexer cache.Indexer) WarehouseLister {
	return &warehouseLister{listers.New[*v1alpha1.Warehouse](indexer, v1alpha1.Resource("warehouse"))}
}

// Warehouses returns an object that can list and get Warehouses.
func (s *warehouseLister) Warehouses(namespace string) WarehouseNamespaceLister {
	return warehouseNamespaceLister{listers.NewNamespaced[*v1alpha1.Warehouse](s.ResourceIndexer, namespace)}
}

// WarehouseNamespaceLister helps list and get Warehouses.
// All objects returned here must be treated as read-only.
type WarehouseNamespaceLister interface {
	// List lists all Warehouses in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.Warehouse, err error)
	// Get retrieves the Warehouse from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.Warehouse, error)
	WarehouseNamespaceListerExpansion
}

// warehouseNamespaceLister implements the WarehouseNamespaceLister
// interface.
type warehouseNamespaceLister struct {
	listers.ResourceIndexer[*v1alpha1.Warehouse]
}
