apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/component: manager
  name: {{ .Values.installation.namespace }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: databend-operator
  namespace: {{ .Values.installation.namespace }}
  labels:
    app.kubernetes.io/component: manager
    app.kubernetes.io/name: databend-operator
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: manager
      app.kubernetes.io/name: databend-operator
  replicas: {{ .Values.manager.replicas }}
  template:
    resources:
      requests:
        cpu: {{ .Values.manager.resources.requests.cpu }}
        memory: {{ .Values.manager.resources.requests.memory }}
      limits:
        cpu: {{ .Values.manager.resources.limits.cpu }}
        memory: {{ .Values.manager.resources.limits.memory }}
    metadata:
      labels:
        app.kubernetes.io/component: manager
        app.kubernetes.io/name: databend-operator
    spec:
      containers:
        - command:
            - /manager
          args:
            - --leader-elect
            - --health-probe-bind-address=:8081
          image: datafuselabs/databend-operator
          name: manager
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
      serviceAccountName: databend-operator
      terminationGracePeriodSeconds: 10
