---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - databendlabs.io
  resources:
  - tenants
  - warehouses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - databendlabs.io
  resources:
  - tenants/finalizers
  - warehouses/finalizers
  verbs:
  - update
- apiGroups:
  - databendlabs.io
  resources:
  - tenants/status
  - warehouses/status
  verbs:
  - get
  - patch
  - update
