# permissions for end users to edit warehouses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: databend-operator
    app.kubernetes.io/managed-by: kustomize
  name: warehouse-editor-role
rules:
- apiGroups:
  - databendlabs.io
  resources:
  - warehouses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - databendlabs.io
  resources:
  - warehouses/status
  verbs:
  - get
