apiVersion: databendlabs.io/v1alpha1
kind: Warehouse
metadata:
  labels:
    app.kubernetes.io/name: databend-operator
    app.kubernetes.io/managed-by: kustomize
  name: warehouse-sample
spec:
  # TODO(user): Add fields here
