/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// LogSpecApplyConfiguration represents a declarative configuration of the LogSpec type for use
// with apply.
type LogSpecApplyConfiguration struct {
	File    *FileLogSpecApplyConfiguration `json:"file,omitempty"`
	Stderr  *FileLogSpecApplyConfiguration `json:"stderr,omitempty"`
	Query   *OTLPLogSpecApplyConfiguration `json:"query,omitempty"`
	Profile *OTLPLogSpecApplyConfiguration `json:"profile,omitempty"`
}

// LogSpecApplyConfiguration constructs a declarative configuration of the LogSpec type for use with
// apply.
func LogSpec() *LogSpecApplyConfiguration {
	return &LogSpecApplyConfiguration{}
}

// WithFile sets the File field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the File field is set to the value of the last call.
func (b *LogSpecApplyConfiguration) WithFile(value *FileLogSpecApplyConfiguration) *LogSpecApplyConfiguration {
	b.File = value
	return b
}

// WithStderr sets the Stderr field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Stderr field is set to the value of the last call.
func (b *LogSpecApplyConfiguration) WithStderr(value *FileLogSpecApplyConfiguration) *LogSpecApplyConfiguration {
	b.Stderr = value
	return b
}

// WithQuery sets the Query field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Query field is set to the value of the last call.
func (b *LogSpecApplyConfiguration) WithQuery(value *OTLPLogSpecApplyConfiguration) *LogSpecApplyConfiguration {
	b.Query = value
	return b
}

// WithProfile sets the Profile field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Profile field is set to the value of the last call.
func (b *LogSpecApplyConfiguration) WithProfile(value *OTLPLogSpecApplyConfiguration) *LogSpecApplyConfiguration {
	b.Profile = value
	return b
}
