/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
)

// S3AuthApplyConfiguration represents a declarative configuration of the S3Auth type for use
// with apply.
type S3AuthApplyConfiguration struct {
	SecretKey *string             `json:"secretKey,omitempty"`
	AccessKey *string             `json:"accessKey,omitempty"`
	SecretRef *v1.ObjectReference `json:"secretRef,omitempty"`
}

// S3AuthApplyConfiguration constructs a declarative configuration of the S3Auth type for use with
// apply.
func S3Auth() *S3AuthApplyConfiguration {
	return &S3AuthApplyConfiguration{}
}

// WithSecretKey sets the SecretKey field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SecretKey field is set to the value of the last call.
func (b *S3AuthApplyConfiguration) WithSecretKey(value string) *S3AuthApplyConfiguration {
	b.SecretKey = &value
	return b
}

// WithAccessKey sets the AccessKey field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AccessKey field is set to the value of the last call.
func (b *S3AuthApplyConfiguration) WithAccessKey(value string) *S3AuthApplyConfiguration {
	b.AccessKey = &value
	return b
}

// WithSecretRef sets the SecretRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SecretRef field is set to the value of the last call.
func (b *S3AuthApplyConfiguration) WithSecretRef(value v1.ObjectReference) *S3AuthApplyConfiguration {
	b.SecretRef = &value
	return b
}
