/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// TenantSpecApplyConfiguration represents a declarative configuration of the TenantSpec type for use
// with apply.
type TenantSpecApplyConfiguration struct {
	StorageApplyConfiguration `json:",inline"`
	Meta                      *MetaConfigApplyConfiguration `json:"meta,omitempty"`
	Users                     []UserApplyConfiguration      `json:"users,omitempty"`
}

// TenantSpecApplyConfiguration constructs a declarative configuration of the TenantSpec type for use with
// apply.
func TenantSpec() *TenantSpecApplyConfiguration {
	return &TenantSpecApplyConfiguration{}
}

// WithS3 sets the S3 field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the S3 field is set to the value of the last call.
func (b *TenantSpecApplyConfiguration) WithS3(value *S3StorageApplyConfiguration) *TenantSpecApplyConfiguration {
	b.S3 = value
	return b
}

// WithMeta sets the Meta field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Meta field is set to the value of the last call.
func (b *TenantSpecApplyConfiguration) WithMeta(value *MetaConfigApplyConfiguration) *TenantSpecApplyConfiguration {
	b.Meta = value
	return b
}

// WithUsers adds the given value to the Users field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Users field.
func (b *TenantSpecApplyConfiguration) WithUsers(values ...*UserApplyConfiguration) *TenantSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithUsers")
		}
		b.Users = append(b.Users, *values[i])
	}
	return b
}
