/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/databendcloud/databend-operator/pkg/apis/databendlabs.io/v1alpha1"
	v1 "k8s.io/api/core/v1"
)

// UserApplyConfiguration represents a declarative configuration of the User type for use
// with apply.
type UserApplyConfiguration struct {
	Name                *string                `json:"name,omitempty"`
	AuthType            *v1alpha1.UserAuthType `json:"authType,omitempty"`
	AuthString          *string                `json:"authString,omitempty"`
	AuthStringSecretRef *v1.ObjectReference    `json:"authStringSecretRef,omitempty"`
}

// UserApplyConfiguration constructs a declarative configuration of the User type for use with
// apply.
func User() *UserApplyConfiguration {
	return &UserApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *UserApplyConfiguration) WithName(value string) *UserApplyConfiguration {
	b.Name = &value
	return b
}

// WithAuthType sets the AuthType field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AuthType field is set to the value of the last call.
func (b *UserApplyConfiguration) WithAuthType(value v1alpha1.UserAuthType) *UserApplyConfiguration {
	b.AuthType = &value
	return b
}

// WithAuthString sets the AuthString field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AuthString field is set to the value of the last call.
func (b *UserApplyConfiguration) WithAuthString(value string) *UserApplyConfiguration {
	b.AuthString = &value
	return b
}

// WithAuthStringSecretRef sets the AuthStringSecretRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AuthStringSecretRef field is set to the value of the last call.
func (b *UserApplyConfiguration) WithAuthStringSecretRef(value v1.ObjectReference) *UserApplyConfiguration {
	b.AuthStringSecretRef = &value
	return b
}
