name: Setup E2E test template
description: A composite action to setup e2e tests

inputs:
  kubernetes-version:
    required: true
    description: Kubernetes version

runs:
  using: composite
  steps:
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod

    - name: Create k8s Kind Cluster
      uses: helm/kind-action@v1.11.0
      with:
        node_image: kindest/node:${{ inputs.kubernetes-version }}
        cluster_name: databend-operator-cluster
        kubectl_version: ${{ inputs.kubernetes-version }}

    - name: Build Databend Operator
      shell: bash
      run: |
        ./scripts/gha/build-image.sh
      env:
        OPERATOR_CI_IMAGE: datafuselabs/databend-operator:test

    - name: Setup Cluster
      shell: bash
      run: |
        ./scripts/gha/setup-cluster.sh
      env:
        KIND_CLUSTER: databend-operator-cluster
        OPERATOR_CI_IMAGE: datafuselabs/databend-operator:test
        KUBERNETES_VERSION: ${{ inputs.kubernetes-version }}
