name: Setup E2E test template
description: A composite action to setup e2e tests

inputs:
  kubernetes-version:
    required: true
    description: Kubernetes version

runs:
  using: composite
  steps:
    # This step is a Workaround to avoid the "No space left on device" error.
    # ref: https://github.com/actions/runner-images/issues/2840
    - name: Remove unnecessary files
      shell: bash
      run: |
        echo "Disk usage before cleanup:"
        df -hT

        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        sudo rm -rf /usr/local/share/boost
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"
        sudo rm -rf /usr/local/lib/android
        sudo rm -rf /usr/local/share/powershell
        sudo rm -rf /usr/share/swift

        echo "Disk usage after cleanup:"
        df -hT

    - name: Prune docker images
      shell: bash
      run: |
        docker image prune -a -f
        docker system df
        df -hT

    - name: Move docker data directory
      shell: bash
      run: |
        echo "Stopping docker service ..."
        sudo systemctl stop docker
        DOCKER_DEFAULT_ROOT_DIR=/var/lib/docker
        DOCKER_ROOT_DIR=/mnt/docker
        echo "Moving ${DOCKER_DEFAULT_ROOT_DIR} -> ${DOCKER_ROOT_DIR}"
        sudo mv ${DOCKER_DEFAULT_ROOT_DIR} ${DOCKER_ROOT_DIR}
        echo "Creating symlink ${DOCKER_DEFAULT_ROOT_DIR} -> ${DOCKER_ROOT_DIR}"
        sudo ln -s ${DOCKER_ROOT_DIR} ${DOCKER_DEFAULT_ROOT_DIR}
        echo "$(sudo ls -l ${DOCKER_DEFAULT_ROOT_DIR})"
        echo "Starting docker service ..."
        sudo systemctl daemon-reload
        sudo systemctl start docker
        echo "Docker service status:"
        sudo systemctl --no-pager -l -o short status docker

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod

    - name: Create k8s Kind Cluster
      uses: helm/kind-action@v1.11.0
      with:
        node_image: kindest/node:${{ inputs.kubernetes-version }}
        cluster_name: databend-operator-cluster
        kubectl_version: ${{ inputs.kubernetes-version }}

    - name: Build Databend Operator
      shell: bash
      run: |
        ./scripts/gha/build-image.sh
      env:
        OPERATOR_CI_IMAGE: datafuselabs/databend-operator:test

    - name: Deploy Databend Operator
      shell: bash
      run: |
        ./scripts/gha/setup-databend-operator.sh
        docker system prune -a -f
        docker system df
        df -h
      env:
        KIND_CLUSTER: databend-operator-cluster
        OPERATOR_CI_IMAGE: datafuselabs/databend-operator:test
        KUBERNETES_VERSION: ${{ inputs.kubernetes-version }}
