name: E2E Test with Deploying Tenant and Warehouse
on:
  - pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  e2e-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        kubernetes-version: ["1.29.14", "1.30.0", "1.31.0"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup E2E Tests
        uses: ./.github/workflows/template-e2e-test
        with:
          kubernetes-version: ${{ matrix.kubernetes-version }}
