name: E2E Test with on Kind Cluster
on:
  - pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  e2e-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        k3d-version: ["v5.6.0", "v5.7.0", "v5.8.0"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup E2E Tests
        uses: ./.github/workflows/template-e2e-test-k3d
        with:
          k3d-version: ${{ matrix.k3d-version }}
      
      - name: Run E2E Tests
        run: |
          make test-e2e
