apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: databend-operator
    app.kubernetes.io/managed-by: kustomize
  name: databend-operator-controller-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: databend-operator-controller-manager
subjects:
- kind: ServiceAccount
  name: databend-operator
